### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mgurley** [xml4r/libxml-ruby#98] opened 2014-11-19 12:46 UTC
Not sure if this is a memory leak or an ignorance reveal.  I am using Ruby. 2.12 and experiencing what seems to be a memory leak with the following libxml-ruby code for version 2.7.0:

```ruby
require 'xml'
def generate_row(data=nil)
  row = XML::Node.new('Row')
  if data
    cell = generate_cell(data)
    row << cell
  end
  row
end

def generate_cell(data)
  cell = XML::Node.new('Cell')
  cell << generate_data(data)
  cell
end

def generate_data(data=nil)
  xml_data = XML::Node.new('Data', data.to_s)
  XML::Attr.new(xml_data, 'ss:Type', 'String')
  xml_data
end

(0...100000).to_a.each do |i|
  generate_row('little my')
end
```
The interator calling generate_row allocates 100mb of memory every time.  And never seems to be capable of being garbage collected.

If I replace it with the following hideosity, then the iterator calling generate_row allocates less than 1mb every time (a 1mb that seems to be capable of being garbage collected):

 ```ruby
def generate_row(style ='open', data = nil)
  row = ''
  if (style == 'open' || style == 'both')
    row = '<Row>'
  end

  if data
    cell = generate_cell(data)
    row = row + cell
  end

  if (style == 'close' || style == 'both')
    row = row + '</Row>'
  end

  row
end

def generate_cell(data)
  cell = '<Cell>'
  cell = cell + generate_data(data)
  cell = cell + '</Cell>'
  cell
end

def generate_data(data='')
  xml_data = '<Data ss:Type="String">'
  xml_data = xml_data + data.to_s.encode(xml: :text) + '</Data>'
end

(0...100000).to_a.each do |i|
  generate_row('little my')
end
```

**Comment by BitBrit** [comment] 2016-04-12 18:49
Has anyone had a chance to look into this?  The reason I ask is that I am experiencing very similar behaviour.  I have a memory leak somewhere in my application and I have traced it down to the XML handling part and to parts which create XML::Node objects.  

I am using MRI ruby 1.9.3-p551 and libxml-ruby 2.8.0.   I have used ObjectSpace to keep track of the object counts and there doesn't seem be any issue with objects not being GC'd. It's like there are objects that the GC doesn't know to clean up. Is that possible?

**Comment by cfis** [comment] 2016-06-12 07:57
See #106.  Note there actually was a memory leaks also, fixed in bdf7832d9590f10fe4464904bd0ee5a7b3fed150.  But that wasn't the cause of this issue.

**Closed by cfis** 2016-06-12 07:57 UTC

**Comment by mgurley** [comment] 2016-06-12 23:45
@cfis  Out of curiosity, was my example not revealing a memory leak?  But instead pointing to user error?

**Comment by cfis** [comment] 2016-06-13 07:01
Although there was a memory leak, that wasn't the issue.  The issue was unsetting the node's mark function - see 4b775b37b7b5c53c39c29b5fae78cdd06a72486c.

I just got lucky finding it.  Most of the time the program would be fine, but sometimes it would end up in an endless marking loop upon calling the garbage collector. And the GCC optimization level seemed to make a difference also. But once I remove the code that unset the mark function everything worked as it should all the time.
