### ISSUE TITLE
Test failures for libxml 2.7.0 with libxml2-2.9.2

### ISSUE THREAD

**Issue by graaff** [xml4r/libxml-ruby#103] opened 2014-12-02 18:44 UTC
With libxml2 2.9.2 I'm getting the following test failures with the released version of libxml 2.7.0:

```
  1) Failure:
test_default_options(TestHtmlParserContext) [/var/tmp/portage/dev-ruby/libxml-2.7.0-r2/work/ruby19/libxml-2.7.0/test/tc_html_parser_context.rb:10]:
<0> expected but was
<256>.

  2) Failure:
test_no_options(TestHtmlParserContext) [/var/tmp/portage/dev-ruby/libxml-2.7.0-r2/work/ruby19/libxml-2.7.0/test/tc_html_parser_context.rb:16]:
<0> expected but was
<256>.

  3) Failure:
test_options(TestHtmlParserContext) [/var/tmp/portage/dev-ruby/libxml-2.7.0-r2/work/ruby19/libxml-2.7.0/test/tc_html_parser_context.rb:22]:
<32> expected but was
<288>.

  4) Failure:
test_bad_xml(TestParser) [/var/tmp/portage/dev-ruby/libxml-2.7.0-r2/work/ruby19/libxml-2.7.0/test/tc_parser.rb:305]:
<20> expected but was
<34>.
```

With libxml2 2.9.1 the test suite passes.

**Comment by graaff** [comment] 2015-01-15 06:59
I'm seeing these test failures also with libxml-ruby 2.8.0.

**Comment by cfis** [comment] 2016-06-12 08:17
Hmm, not able to reproduce anymore.  So closing.

**Closed by cfis** 2016-06-12 08:17 UTC

**Comment by graaff** [comment] 2016-06-14 04:31
I no longer see them with libxml 2.9.0 and libxml2 2.9.4.

**Comment by cfis** [comment] 2016-06-14 04:38
Good to hear - thanks!
