### ISSUE TITLE
Error parsing documentation when installing libxml-ruby-3.2.3

### ISSUE THREAD

**Issue by xyzzy-plugh-plover** [xml4r/libxml-ruby#193] opened 2022-10-26 12:12 UTC
```
$ sudo gem install libxml-ruby 
Fetching libxml-ruby-3.2.3.gem
Building native extensions. This could take a while...
Successfully installed libxml-ruby-3.2.3
Parsing documentation for libxml-ruby-3.2.3
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -c ext/libxml/extconf.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

On macOS 12.6.1 with:

```
$ ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin21]

$ gem --version
3.2.5

$ rdoc --version
6.4.0
```

**Comment by cfis** [comment] 2022-10-30 08:46
Hmm, not sure. I've never seen this and running rake rdoc I can't reproduce it.

**Comment by PierceLBrooks** [comment] 2023-05-24 21:37
I have been able to reproduce this on an Intel iMac with a Homebrew-installed LibXML package ( version 2.11.4 ):
```
Pierces-iMac:Development piercebrooks$ brew list --versions | grep libxml
libxml2 2.11.4
Pierces-iMac:Development piercebrooks$ sudo gem install libxml-ruby -- --with-xml2-config=/usr/local/opt/libxml2/bin/xml2-config
Password:
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
Fetching libxml-ruby-4.1.1.gem
Building native extensions with: '--with-xml2-config=/usr/local/opt/libxml2/bin/xml2-config'
This could take a while...
Successfully installed libxml-ruby-4.1.1
Parsing documentation for libxml-ruby-4.1.1
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -c ext/libxml/extconf.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

**Comment by PierceLBrooks** [comment] 2023-05-24 22:06
> I have been able to reproduce this on an Intel iMac with a Homebrew-installed LibXML package ( version 2.11.4 ):

This also occurs with my ARM M1 Macbook Pro that has pretty much identical versions of everything involved here.

**Comment by cfis** [comment] 2023-05-25 05:57
Cool. Can you determine which file is causing it? Maybe just run rake  just run `rake rdoc` ?

**Comment by PierceLBrooks** [comment] 2023-05-25 16:16
A simple `rake` command did not suffice, as it ended up being confused about some unit test `require` statements referring to `libxml_ruby` instead of `libxml-ruby`. I instead tried the `bundle exec rake compile` command from `~/libxml-ruby/.github/workflows/mri.yml`, which caused the build to succeed. Afterwards, `rake rdoc` was able to execute successfully with no indication of which file is responsible for this issue. However the culprit is ultimately almost certainly `~/libxml-ruby/ext/libxml/extconf.rb`. Perhaps an even better solution than my pull request would be to add another search path for external library & header inclusion according to a couple superdirectories above whichever directory is specified by the package installation user with `--with-xml2-config`.

**Comment by cfis** [comment] 2023-05-30 01:47
Strange that is fine on Windows and Linux. Seems to only happen on MacOS?

**Comment by nieder** [comment] 2023-09-06 10:43
Seems to be a ruby26 issue, because I get the same error installing the gem against ruby26, but it works with ruby27 and ruby32 using otherwise identical gem install commands and all 3rd party rubymods removed to avoid pollution.
```
/sw/bin/gem2.6 install \
	--local \
	--force \
	--verbose \
	--vendor \
	--platform=x86_64-apple-darwin \
	--build-root /sw/build.build/root-libxml2-rb26-4.1.1-1 \
	--document rdoc \
	--ignore-dependencies \
	libxml-ruby-4.1.1.gem \
	-- --with-xml2-config=/sw/bin/xml2-config
```
ruby26: 2.6.10p210
rdoc: 6.1.2.1
ruby27: 2.7.8p225
rdoc: 6.2.1.1
libxml2: v2.9.14

I'm also on macOS, but using Fink provided libraries and ruby.

**Comment by cfis** [comment] 2024-01-08 20:09
Since Ruby 2.6 is no longer supported (although I know MacOS ships with it), going to close this.

**Closed by cfis** 2024-01-08 20:09 UTC
